# frozen_string_literal: true

# GENERATED by scripts/generate_icons.rb — do not hand-edit; re-run the
# generator to refresh or expand. Path data (c) Lucide contributors,
# ISC (some Feather-derived icons MIT) — see THIRD_PARTY_LICENSES. Source: github.com/lucide-icons/lucide.
module PhlexKit
  module Icons
    module Lucide
      VIEW_BOX = "0 0 24 24"
      MODE = :stroke
      STROKE_WIDTH = 2
      ICONS = {
        chevron_down: [ [ :path, { d: "m6 9 6 6 6-6" } ] ],
        chevron_up: [ [ :path, { d: "m18 15-6-6-6 6" } ] ],
        chevron_left: [ [ :path, { d: "m15 18-6-6 6-6" } ] ],
        chevron_right: [ [ :path, { d: "m9 18 6-6-6-6" } ] ],
        chevrons_up_down: [ [ :path, { d: "m7 15 5 5 5-5" } ], [ :path, { d: "m7 9 5-5 5 5" } ] ],
        check: [ [ :path, { d: "M20 6 9 17l-5-5" } ] ],
        x: [ [ :path, { d: "M18 6 6 18" } ], [ :path, { d: "m6 6 12 12" } ] ],
        search: [ [ :path, { d: "m21 21-4.34-4.34" } ], [ :circle, { cx: "11", cy: "11", r: "8" } ] ],
        ellipsis: [ [ :circle, { cx: "12", cy: "12", r: "1" } ], [ :circle, { cx: "19", cy: "12", r: "1" } ], [ :circle, { cx: "5", cy: "12", r: "1" } ] ],
        arrow_left: [ [ :path, { d: "m12 19-7-7 7-7" } ], [ :path, { d: "M19 12H5" } ] ],
        arrow_right: [ [ :path, { d: "M5 12h14" } ], [ :path, { d: "m12 5 7 7-7 7" } ] ],
        loader: [ [ :path, { d: "M21 12a9 9 0 1 1-6.219-8.56" } ] ],
        circle_check: [ [ :circle, { cx: "12", cy: "12", r: "10" } ], [ :path, { d: "m9 12 2 2 4-4" } ] ],
        circle_x: [ [ :circle, { cx: "12", cy: "12", r: "10" } ], [ :path, { d: "m15 9-6 6" } ], [ :path, { d: "m9 9 6 6" } ] ],
        triangle_alert: [ [ :path, { d: "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" } ], [ :path, { d: "M12 9v4" } ], [ :path, { d: "M12 17h.01" } ] ],
        info: [ [ :circle, { cx: "12", cy: "12", r: "10" } ], [ :path, { d: "M12 16v-4" } ], [ :path, { d: "M12 8h.01" } ] ],
      }.freeze
    end
  end
end
