# frozen_string_literal: true

# GENERATED by scripts/generate_icons.rb — do not hand-edit; re-run the
# generator to refresh or expand. Path data (c) Tabler contributors,
# MIT — see THIRD_PARTY_LICENSES. Source: github.com/tabler/tabler-icons.
module PhlexKit
  module Icons
    module Tabler
      VIEW_BOX = "0 0 24 24"
      MODE = :stroke
      STROKE_WIDTH = 2
      ICONS = {
        chevron_down: [ [ :path, { d: "M6 9l6 6l6 -6" } ] ],
        chevron_up: [ [ :path, { d: "M6 15l6 -6l6 6" } ] ],
        chevron_left: [ [ :path, { d: "M15 6l-6 6l6 6" } ] ],
        chevron_right: [ [ :path, { d: "M9 6l6 6l-6 6" } ] ],
        chevrons_up_down: [ [ :path, { d: "M8 9l4 -4l4 4" } ], [ :path, { d: "M16 15l-4 4l-4 -4" } ] ],
        check: [ [ :path, { d: "M5 12l5 5l10 -10" } ] ],
        x: [ [ :path, { d: "M18 6l-12 12" } ], [ :path, { d: "M6 6l12 12" } ] ],
        search: [ [ :path, { d: "M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" } ], [ :path, { d: "M21 21l-6 -6" } ] ],
        ellipsis: [ [ :path, { d: "M4 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" } ], [ :path, { d: "M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" } ], [ :path, { d: "M18 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" } ] ],
        arrow_left: [ [ :path, { d: "M5 12l14 0" } ], [ :path, { d: "M5 12l6 6" } ], [ :path, { d: "M5 12l6 -6" } ] ],
        arrow_right: [ [ :path, { d: "M5 12l14 0" } ], [ :path, { d: "M13 18l6 -6" } ], [ :path, { d: "M13 6l6 6" } ] ],
        loader: [ [ :path, { d: "M12 3a9 9 0 1 0 9 9" } ] ],
        circle_check: [ [ :path, { d: "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" } ], [ :path, { d: "M9 12l2 2l4 -4" } ] ],
        circle_x: [ [ :path, { d: "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" } ], [ :path, { d: "M10 10l4 4m0 -4l-4 4" } ] ],
        triangle_alert: [ [ :path, { d: "M12 9v4" } ], [ :path, { d: "M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0" } ], [ :path, { d: "M12 16h.01" } ] ],
        info: [ [ :path, { d: "M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0" } ], [ :path, { d: "M12 9h.01" } ], [ :path, { d: "M11 12h1v4h1" } ] ],
      }.freeze
    end
  end
end
